### ISSUE TITLE
Currently not working on Python 3

### ISSUE THREAD

**Issue by stared** [TyberiusPrime/pyggplot#2]
As of now, it does not even load in python3, due to syntax error near `print`.

Using syntax `print(something)` instead of `print something` will solve this problem. Not sure if there are other problematic pieces.

**Comment by TyberiusPrime** [comment]
Fixed. Simple test plot now works in python3, I expect everything else to fall smoothly in line.

Guess we lost support for python <2.7 or whenever the 'except Exceptions as e' syntax was enabled.
Don't particularly care about that though.
