### ISSUE TITLE
Problems to install 

### ISSUE THREAD

**Issue by ferreiraleo** [TyberiusPrime/pyggplot#8]
When I am trying to install this library give me this error on anaconda prompt

WindowsError: [Error 5] Access is denied, 'c:[.....] matplotlib\\backends\\_backend_agg.pyd' 

Can someone help me?

**Comment by TyberiusPrime** [comment]
We're going to need a lot more information - what operating system are you on, how are you installing, what's the full output?

**Comment by TyberiusPrime** [comment]
Your error message suggests that this is an issue installing matplotlib on Windows using Anaconda, and thus far outside of the scope of this package. Since I haven't heard back in 30 days, I'll go ahead and close this issue. Thank you for trying pyggplot.
